version: '3.8'
services:

  clubhub-db:
    image: postgres:16-alpine
    container_name: clubhub-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clubhub
    ports:
      - "15432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db-init:
    image: postgres:16-alpine
    depends_on:
      - clubhub-db
    volumes:
      - ./setup_db.sh:/setup_db.sh
    entrypoint: "/bin/bash"
    command: /setup_db.sh

  app:
    container_name: clubhub
    build: .
    ports:
      - 8001:8001
    depends_on:
      - db-init
    environment:
      - DB_PORT=5432
      - DB_HOST=clubhub-db
      - DB_NAME=clubhub
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    restart: on-failure