info:
  contact: {}
paths:
  /clubhub:
    get:
      consumes:
      - application/json
      description: GetAllAddress We get all the addresses we have consulted.
      produces:
      - application/json
      responses: {}
      summary: Get All Addresses
  /clubhub/address/{address}:
    get:
      consumes:
      - application/json
      description: GetByAddress We get all the information by address
      parameters:
      - description: address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      - application/json
      responses: {}
      summary: We Get By Address
swagger: "2.0"
